 (cd "$(git rev-parse --show-toplevel)" && git apply --3way <<'EOF' 
diff --git a/netlify.toml b/netlify.toml
new file mode 100644
index 0000000000000000000000000000000000000000..b18bc534b7340be2a1df480a0980f344a6a5ffdf
--- /dev/null
+++ b/netlify.toml
@@ -0,0 +1,3 @@
+[build]
+  publish = "."
+  command = ""
 
EOF
)
